/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  meadowSidebar: [{ type: "autogenerated", dirName: "Meadow" }],

  hardwareSidebar: [{ type: "autogenerated", dirName: "Hardware" }],
  
  // FYI, this is how you manually hand curate a custom navbar. Kind of a pain.
  meadowOsSidebar: [
    {
      type: "category",
      label: "Meadow.OS",
      
      items: [
        { type: "doc",
          id:"Meadow/Meadow.OS/index",
          className:"hidden-doc"
      },
        "Meadow/Meadow.OS/Automatic_Restarts/index",
        "Meadow/Meadow.OS/Bluetooth/index",
        "Meadow/Meadow.OS/Cellular/index",
        "Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/index",
        "Meadow/Meadow.OS/Configuration/OS_Device_Configuration/index",
        "Meadow/Meadow.OS/Configuration/WiFi_Configuration/index",
        "Meadow/Meadow.OS/Configuration/index",
        "Meadow/Meadow.OS/Core-Compute_SD_Card/index",
        "Meadow/Meadow.OS/File_System/index",
        "Meadow/Meadow.OS/Networking/Antenna/index",
        "Meadow/Meadow.OS/Networking/index",
        "Meadow/Meadow.OS/RTC/index",
        "Meadow/Meadow.OS/SQLite/index",
        "Meadow/Meadow.OS/Threading/index",
        "Meadow/Meadow.OS/Updates/index",
        "Meadow/Meadow.OS/Watchdog/index",
      ],
    },
    {
      type: "category",
      label: "Release Notes",
      items: [
        "Meadow/Release_Notes/index",
        "Meadow/Release_Notes/Release-Candidates/index",
        "Meadow/Release_Notes/Beta6/index",
        "Meadow/Release_Notes/Beta5/index",
        "Meadow/Release_Notes/Beta4/index",
        "Meadow/Release_Notes/Beta3/index",
        "Meadow/Release_Notes/Beta2/index",
      ],
    },
  ],

};

module.exports = sidebars;
